services:
  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    env_file:
      - project.env
    depends_on:
      - database
      - redis
    deploy:
      mode: replicated
      replicas: 1
    labels:
      - traefik.enable=true
      - traefik.http.routers.server-router.entrypoints=web
      - traefik.http.routers.server-router.rule=PathPrefix(`/api`)
      - traefik.http.services.server-service.loadbalancer.server.port=8000

  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client:/app
    depends_on:
      - server
    labels:
      - traefik.enable=true
      - traefik.http.routers.client-router.entrypoints=web
      - traefik.http.routers.client-router.rule=PathPrefix(`/`)
      - traefik.http.services.client-service.loadbalancer.server.port=4321

  k6-tests:
    entrypoint: "/bin/true"
    build: k6-tests
    volumes:
      - ./k6-tests/tests:/tests
    depends_on:
      - client

  database:
    container_name: postgresql_database
    image: postgres:17.5
    restart: unless-stopped
    env_file:
      - project.env
    command: >
      postgres
      -c shared_preload_libraries=auto_explain,pg_stat_statements
      -c auto_explain.log_min_duration=10
    # log statements that take more than 10ms

  database-migrations:
    image: flyway/flyway:11.10
    env_file:
      - project.env
    depends_on:
      - database
    volumes:
      - ./database-migrations:/flyway/db/migration
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    labels:
      - traefik.enable=false

  redis:
    image: redis:7.4.2
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  traefik:
    image: traefik:v3.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"
      - "--metrics.otlp=true"
      - "--metrics.otlp.http.endpoint=http://lgtm:4318/v1/metrics"
    ports:
      - 8080:8080
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # consumer-server:
  #   build: consumer-server
  #   restart: unless-stopped
  #   volumes:
  #     - ./consumer-server:/app
  #   env_file:
  #     - project.env
  #   depends_on:
  #     - redis
  #     - database

  lgtm:
    image: grafana/otel-lgtm:0.11.14
    ports:
      - "3000:3000"
      - "4318:4318"